# Dependabot configuration file for PNPM workspace
version: 2
updates:
  # Check for updates to npm dependencies in the vscode package
  - package-ecosystem: 'npm'
    directory: '/packages/vscode'
    schedule:
      interval: 'monthly'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
      # Build won't pass when version of @types/vscode does not match engines.vscode
      - dependency-name: '@types/vscode'
        versions: ['*']
    groups:
      workspace-dependencies:
        patterns:
          - '*'

  # Check for updates to npm dependencies in the browser package
  - package-ecosystem: 'npm'
    directory: '/packages/browser'
    schedule:
      interval: 'monthly'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    groups:
      workspace-dependencies:
        patterns:
          - '*'
